docs: CONTRIBUTINGの更新
daiti0113/Joker-frontend pull request #273
Opened 2022-01-07 13:20 UTC by zukeyama0424

2022-01-10 12:05 UTC, zukeyama0424 commented
fix ホームの検索バー及び、タグ検索、使用アイテムの検索バーのstyle修正

2022-01-11 12:15 UTC, misdo-tabeyo requested changes
1箇所使ってないのがimportされてるかも！

2022-01-11 12:15 UTC, misdo-tabeyo commented on src/screens/SearchScreen.js
> +import { autoShowTooltip } from "@aws-amplify/ui"
余計なのが入ってる？？

2022-01-16 02:15 UTC, misdo-tabeyo approved these changes
LGTM

2022-01-16 02:15 UTC, merged